# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 12:56
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('cp', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('stardust', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('stigmata', models.IntegerField()),
                ('percent', models.FloatField()),
                ('app1', models.IntegerField()),
                ('app2S', models.BooleanField()),
                ('app2A', models.BooleanField()),
                ('app2D', models.BooleanField()),
                ('app3', models.IntegerField()),
                ('team', models.CharField(max_length=32)),
                ('ref', models.CharField(default=api.models._createRef, max_length=32, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=32, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
